export const methodBA = () => {
  return "from moduleB.methodBA";
};

export const methodBB = () => {
  return `from moduleB.methodBB
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  abczyxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvabcdxwvucdefg
  `;
};

export const methodBC = () => {
  return "from moduleB.methodBC should be dynamic";
}
